
---

### `config/defaults.yaml`
```yaml
portfolio:
  starting_cash: 1000.0
  allow_fractional: true
  base_currency: USD
risk:
  per_trade_risk_pct: 0.01
  max_daily_drawdown_pct: 0.05
  max_open_positions: 5
  stop_loss_pct: 0.03
  trailing_stop_pct: 0.02
market:
  use_market_hours: true
  exchange: NYSE
  data_mode: replay
  universe: [AAPL, MSFT, NVDA, SPY]
logging:
  export_csv: true
  export_parquet: false
  db_path: data/sqlite/stockapp.db
controller:
  auto_adjust: false
  lookback_days: 5
  min_confidence: 0.6
ui:
  refresh_seconds: 5
